services:
    traefik:
        image: "traefik:v3.0"
        container_name: "traefik"
        command:
            #- "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entryPoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

    laravel:
        build:
            context: ./
            dockerfile: docker/Dockerfile
        container_name: laravel
        hostname: laravel
        volumes:
             - ./:/srv/app
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.entrypoints=web"
            - "traefik.http.routers.laravel.rule=Host(`laravel.localhost`)"
